config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                           sidekiq_web        /sidekiq                                                                                 Sidekiq::Web
#                                  root GET    /                                                                                        home#index
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                             companies GET    /companies(.:format)                                                                     companies#index
#                                       POST   /companies(.:format)                                                                     companies#create
#                           new_company GET    /companies/new(.:format)                                                                 companies#new
#                          edit_company GET    /companies/:id/edit(.:format)                                                            companies#edit
#                               company GET    /companies/:id(.:format)                                                                 companies#show
#                                       PATCH  /companies/:id(.:format)                                                                 companies#update
#                                       PUT    /companies/:id(.:format)                                                                 companies#update
#                                       DELETE /companies/:id(.:format)                                                                 companies#destroy
#                           mycompanies GET    /mycompanies(.:format)                                                                   companies#my_companies
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#                                   pay        /pay                                                                                     Pay::Engine
#
# Routes for Pay::Engine:
#            payment GET  /payments/:id(.:format)       pay/payments#show
#    webhooks_stripe POST /webhooks/stripe(.:format)    stripe_event/webhook#event
# webhooks_braintree POST /webhooks/braintree(.:format) pay/webhooks/braintree#create

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'

Rails.application.routes.draw do
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  root to: 'home#index'
  devise_for :users  
  resources :companies
  
  get 'mycompanies'     => 'companies#my_companies'
end

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title><%= full_title(yield(:title)) %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<header class="sticky top-0 z-50 w-full px-4 py-4 lg:px-0", style="background-color: hsla(0,0%,100%,.9);}">
  <div class="container flex flex-wrap items-center justify-between mx-auto">

    <%= link_to root_path, class:"flex flex-wrap items-center justify-start" do %>
      <h1 class="text-2xl font-black leading-none font-display">Built In Toronto</h1>
      <p class="relative block ml-1 font-sans text-xs italic">Beta</p>
    <% end %>
  
    <div class="block lg:hidden">
      <button type="button" id="mobile-menu" class="flex items-center px-2 text-white lg:px-4 lg:hidden focus:outline-none focus:text-gray-700">
          <svg class="w-6 h-6 text-gray-700 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <title>Menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
          </svg>
      </button>
    </div>

    <ul class="flex-wrap justify-start block lg:flex">
      <li class="py-2 text-center lg:pl-2 lg:py-0 lg:text-left"><%= link_to "All Companies", companies_path, class: "w-full text-lg btn btn-transparent lg:w-auto lg:text-sm" %></li>
      <li class="py-2 text-center lg:pl-2 lg:py-0 lg:text-left"><%= link_to "My companies", mycompanies_path, class: "w-full text-lg btn btn-transparent lg:w-auto lg:text-sm" %></li>            
    </ul>


    <nav class="hidden w-full lg:block lg:w-auto" id="main-nav">
      <ul class="flex-wrap items-center justify-start block lg:flex">
        <% if user_signed_in? %>
          <li class="py-2 text-center lg:pl-2 lg:py-0 lg:text-left"><%= link_to "Edit account", edit_user_registration_path, class: "w-full text-lg btn btn-transparent lg:w-auto lg:text-sm"  %></li>
          <li class="py-2 text-center lg:pl-2 lg:py-0 lg:text-left"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "w-full text-lg btn btn-transparent lg:w-auto lg:text-sm" %></li>
                    
          <% else %>
          
          <li class="py-2 text-center lg:pl-2 lg:py-0 lg:text-left"><%= link_to "Login", new_user_session_path, class:"w-full text-lg btn btn-transparent lg:w-auto lg:text-sm" %></li>
          <li class="py-2 text-center lg:pl-2 lg:py-0 lg:text-left"><%= link_to "Sign Up", new_user_registration_path, class:"w-full text-lg btn btn-transparent lg:w-auto lg:text-sm" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>