config/routes.rb
# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                           sidekiq_web        /sidekiq                                                                                 Sidekiq::Web
#                                  root GET    /                                                                                        home#index
#                      new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#                          user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#                  destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#                     new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#                    edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#                         user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                                       PUT    /users/password(.:format)                                                                devise/passwords#update
#                                       POST   /users/password(.:format)                                                                devise/passwords#create
#              cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#                 new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#                edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#                     user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                                       PUT    /users(.:format)                                                                         devise/registrations#update
#                                       DELETE /users(.:format)                                                                         devise/registrations#destroy
#                                       POST   /users(.:format)                                                                         devise/registrations#create
#                             companies GET    /companies(.:format)                                                                     companies#index
#                                       POST   /companies(.:format)                                                                     companies#create
#                           new_company GET    /companies/new(.:format)                                                                 companies#new
#                          edit_company GET    /companies/:id/edit(.:format)                                                            companies#edit
#                               company GET    /companies/:id(.:format)                                                                 companies#show
#                                       PATCH  /companies/:id(.:format)                                                                 companies#update
#                                       PUT    /companies/:id(.:format)                                                                 companies#update
#                                       DELETE /companies/:id(.:format)                                                                 companies#destroy
#                           mycompanies GET    /mycompanies(.:format)                                                                   companies#my_companies
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#   rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#health_check
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#                                   pay        /pay                                                                                     Pay::Engine
#
# Routes for Pay::Engine:
#            payment GET  /payments/:id(.:format)       pay/payments#show
#    webhooks_stripe POST /webhooks/stripe(.:format)    stripe_event/webhook#event
# webhooks_braintree POST /webhooks/braintree(.:format) pay/webhooks/braintree#create

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'

Rails.application.routes.draw do
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  root to: 'home#index'
  devise_for :users  
  resources :companies
  
  get 'mycompanies'     => 'companies#my_companies'
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :bigint           not null, primary key
#  email      :string
#  found_date :date
#  name       :string
#  slug       :string           indexed
#  website    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null, indexed
#
# Indexes
#
#  index_companies_on_slug     (slug) UNIQUE
#  index_companies_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Company < ApplicationRecord
  include Sluggable

  # association 
  belongs_to :user, optional: true
  has_rich_text :details
  has_one_attached :logo
  has_many_attached :photos, dependent: :destroy


  # include FriendlyId
  # friendly_id :name, use: [:slugged, :finders]
  # # Friendly_Id code to only update the url for new records
  # def should_generate_new_friendly_id?
  #   new_record? || slug.blank?
  # end

  def slug_candidates
    [:name]
  end 

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # validatation
  validates           :name,                presence: true, uniqueness: {case_sensitive: true}
  validates_length_of :name,                maximum: 80,    allow_blank: false
  validates           :details,             presence: true
  validates           :email,               presence: true
  validates           :logo,                presence: true
  validates           :website,             presence: true
  validates           :found_date,          presence: true
  validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  respond_to :html

  load_and_authorize_resource

  def index
    @companies = Company.all
    respond_with(@companies)
  end

  def show
    respond_with(@company)
    redirect_to_slug(action: :show, object: set_company)
  end

  def new
    @company = Company.new
    respond_with(@company)
  end

  def edit
    if current_user.id == @company.user_id
      render :edit
    else
      respond_with company_path, notice: "You don't have permission! 🚫"
    end
  end

  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    @company.save
    respond_with(@company)
  end

  def update
    @company.update(company_params)
    respond_with(@company)
  end

  def destroy
    @company.destroy
    respond_with(@company)
  end

  def my_companies
    @my_companies = current_user.companies
  end


  private
    def set_company
      @company = Company.friendly.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name, :details, :email, :website, :found_date, :logo)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, multipart: true, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2 class="font-bold text-red-500"><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-6">
    <%= form.label :logo, "Comapny logo", class: "label" %>
    <%= form.file_field :logo %>
  </div>

  <div class="mb-6">
    <%= form.label :name, "Company Name", class: "label" %>
    <%= form.text_field :name, class: "input", required: 'required', placeholder: "Company Name" %>
  </div>

  <div class="mb-6">
    <%= form.label :details, "Company info", class: "label" %>
    <%= form.rich_text_area :details, class: "input", required: 'required', placeholder: "Enter your company or organization’s mission statement. This will be displayed on your company’s profile." %>
  </div>

  <div class="mb-6">
    <%= form.label :email, "Email", class: "label" %>
    <%= form.text_field :email, class: "input", required: 'required', placeholder: "We’ll send your receipt and confirmation email here." %>
  </div>

  <div class="mb-6">
    <%= form.label :website, "Company's Website URL", class: "label" %>
    <%= form.text_field :website, class: "input", required: 'required', placeholder: "Example: https://mybusiness.com/" %>
  </div>

  <div class="mb-6">
    <%= form.label :found_date, "Founded Date", class: "label" %>
    <%= form.date_select :found_date, class: "input", required: 'required', placeholder: "When your company was founded" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="container flex flex-wrap items-center justify-center mx-auto">
  <p id="notice"><%= notice %></p>
  <div class="w-full pt-0 pb-10 text-center">
    <h1 class="w-full max-w-2xl mx-auto text-4xl font-black leading-none lg:text-5xl font-display">Toronto Companies</h1>
    <p class="max-w-xl pt-4 mx-auto mb-6 text-xl leading-normal opacity-75">Experience the startup ecosystem — invest in startups, research the fastest-growing companies, and find a job you love.</p>
    <a href="#" class="w-full px-5 mb-4 text-lg cursor-pointer btn lg:text-sm lg:w-auto btn-black lg:mr-2 lg:mb-0">Join The Community</a>
    <a href="#" class="w-full px-5 text-lg cursor-pointer btn btn-black btn-outline lg:text-sm lg:w-auto lg:ml-2">Learn More about the Community</a>
  </div>
</div>



<div class="flex flex-wrap items-start justify-start">
  <% @companies.each do |company| %>
    <div class="relative w-full p-6 border-2 border-blue-700 rounded-lg lg:w-1/4 lg:mr-8">
      <%= image_tag company.logo.variant(resize_to_limit: [600, 400]), class: "rounded" if company.logo.present? %>
      <h3 class="mb-2 text-2xl font-bold"><%= company.name %></h3>
      <div class="my-1"><%= truncate(strip_tags(company.details.to_s), length: 140) %></div>
      <p>Email: <%= company.email %></p>
      <p>Webiste: <%= company.website %></p>
      <p>Found Date: <%= company.found_date %></p>
      <p class="text-sm italic opacity-75">Created by: <%= company.user.email %> </p>
      <%= link_to "View company", company, class: "btn btn-default inline-block text-center my-2" %>
       <% if can? :manage, company %>  
      <div class="absolute top-0 right-0 mt-2 mr-2">
        <%= link_to edit_company_path(company) do %>
          <svg class="w-6 h-6 text-white opacity-75 fill-current" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
          <title>edit</title><path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"></path></svg>
        <% end %>
      </div>
      <% end %>
    </div>
  <% end %>
</div>





  <%= link_to 'New Company', new_company_path, class: "w-full px-5 mb-4 text-lg cursor-pointer btn lg:text-sm lg:w-auto btn-black lg:mr-2 lg:mb-0" %>

</div>



<%#if can? :read, @post %>
  <%#= link_to "View", @post %>
<%# end %>


<%# if current_user.has_role? :admin %>

app/views/companies/my_companies.html.erb
<h1>
  My Companies
</h1>
<br>
<hr>
<br>

<table class="table">
  <thread>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>details</th>
      <th colspan="3"></th>
    </tr>
  </thread>

  <tbody>
    <% @my_companies.each do |company| %>
    <td><%= company.name %></td>
    <td><%= company.email %></td>
    <td><%= company.details %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company), class: 'btn btn-edit' %></td>
    <td><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-destroy' %></td>
  </tbody>
  <% end %>
</table>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="container relative p-6 mx-auto text-gray-900 bg-white rounded-lg lg:p-10" id=<%= company_path(@company.id) %>>
  <div class="flex flex-wrap items-center justify-between w-full pb-4 mb-8">
      <div class="flex-1">
        <h1 class="text-3xl font-bold leading-none text-gray-800"><%= @company.name %></h1>
        <p class="text-sm italic text-gray-500">Created by <%= @company.user.email ||=
      @company.user.username %></p>
      </div>


      <div class="flex flex-wrap items-start justify-between w-full mb-6">
        <div class="w-full lg:w-2/5">
          <% if @company.logo.present? %>
            <%= image_tag @company.logo, class: "rounded" %>
          <% else %>
            <div class="flex items-center justify-center p-8 text-center bg-gray-100 rounded">
              <div class="">
                <p class="text-xs font-bold text-gray-600 uppercase">COMPANY Logo Placment</p>
                <h3 class="text-2xl text-black"><%= @company.name %></h3>
              </div>
            </div>
          <% end %>
        </div>

        <div class="w-full mt-6 lg:pl-10 lg:w-3/5 lg:mt-0">
          <div class="mb-6">
            <p class="text-sm font-semibold text-gray-500 uppercase">Details</p>
            <%= @company.details %>
          </div>        

          <div class="mb-6">
            <p class="text-sm font-semibold text-gray-500 uppercase">Email</p>
            <%= @company.email %>
          </div>        

          <div class="mb-6">
            <p class="text-sm font-semibold text-gray-500 uppercase">Webiste</p>
            <%= @company.website %>
          </div>        
          <div class="mb-6">
            <p class="text-sm font-semibold text-gray-500 uppercase">Founded Date</p>
            <%= @company.found_date %>
          </div>           
          
        </div>     

      </div>

  
  </div> 

 <% if can? :manage, @company %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
      <%= link_to 'Edit', edit_company_path(@company), class: "btn btn-sm btn-outlined btn-default" %>
      <%= link_to 'Delete', company_path(@company), method: :delete, class: "btn btn-sm btn-outlined btn-default", data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>         